// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMuXW3-rXtigeGmSFVYeKupPEqZkQQ2Lc',
    appId: '1:1033148419273:web:1508dc9ffdea9a2e771118',
    messagingSenderId: '1033148419273',
    projectId: 'oqua-235c1',
    authDomain: 'oqua-235c1.firebaseapp.com',
    storageBucket: 'oqua-235c1.firebasestorage.app',
    measurementId: 'G-JDHBF3CTPH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBUSyxjqAneqRIX9txo_9MWQIA9h6PEaY',
    appId: '1:1033148419273:android:1af25f48b8449352771118',
    messagingSenderId: '1033148419273',
    projectId: 'oqua-235c1',
    storageBucket: 'oqua-235c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkc6UHdC6I1VqNaTzoa8_4CokmfnmLjIw',
    appId: '1:1033148419273:ios:d542f9c898a73835771118',
    messagingSenderId: '1033148419273',
    projectId: 'oqua-235c1',
    storageBucket: 'oqua-235c1.firebasestorage.app',
    iosBundleId: 'com.example.natatorioApp',
  );
}
